# Generated by Django 5.1.2 on 2024-11-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='us',
            old_name='stage',
            new_name='step',
        ),
    ]
