# Generated by Django 5.1.2 on 2024-11-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('us', '0002_rename_stage_us_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='us',
            name='last_level_downgrade',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
