# Generated by Django 5.1.2 on 2024-11-04 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_purchase_user'),
        ('users', '0004_alter_user_order_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='order_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='market.purchase'),
        ),
    ]
