# Generated by Django 5.1.2 on 2024-11-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=100)),
                ('ad_image', models.ImageField(upload_to='advertisements/')),
                ('ad_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('price', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='items/')),
                ('item_type', models.CharField(choices=[('sticker', '스티커'), ('theme', '테마'), ('frame', '프레임')], max_length=10)),
                ('note', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
