# Generated by Django 5.1.2 on 2024-11-07 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_purchase_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
    ]
