# Generated by Django 5.0.3 on 2024-10-30 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='card/')),
                ('explanation', models.TextField(max_length=500)),
                ('keyword', models.CharField(choices=[('DISPOSABLES', '일회용품'), ('RECYCLING', '분리수거'), ('TUMBLER', '텀블러'), ('STANDBY_POWER', '대기전력'), ('OTHER', '기타')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
