# Generated by Django 5.0.3 on 2024-10-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_cardpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_card_completed',
            field=models.BooleanField(default=False),
        ),
    ]
