# Generated by Django 5.0.3 on 2024-10-30 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='Frame_completed',
            field=models.BooleanField(default=False),
        ),
    ]
