# Generated by Django 5.0.3 on 2024-10-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0005_frame_frame_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frame',
            old_name='Frame_completed',
            new_name='frame_completed',
        ),
    ]
