# Generated by Django 5.0.3 on 2024-10-31 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0010_alter_photo_card_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='point',
            field=models.IntegerField(default=50, verbose_name='적립금'),
        ),
    ]
