# Generated by Django 5.0.3 on 2024-11-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0011_photo_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=100, verbose_name='적립금')),
            ],
        ),
    ]
