# Generated by Django 5.0.3 on 2024-11-01 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0012_imageshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageshare',
            name='card_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='join.cardpost'),
        ),
    ]
