# Generated by Django 5.0.3 on 2024-11-02 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0013_imageshare_card_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtering', to='join.cardpost')),
            ],
        ),
    ]
