# Generated by Django 5.0.3 on 2024-11-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0014_filtering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filtering',
        ),
    ]
