# Generated by Django 5.0.3 on 2024-11-03 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0017_alter_frame_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='cardpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='join.cardpost'),
        ),
    ]
