# Generated by Django 5.0.3 on 2024-11-04 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0016_alter_cardpost_author'),
        ('join', '0018_frame_cardpost'),
    ]

    operations = [
    ]
