# Generated by Django 5.0.3 on 2024-11-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0019_merge_0016_alter_cardpost_author_0018_frame_cardpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
