# Generated by Django 5.0.3 on 2024-11-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0021_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
