# Generated by Django 5.0.3 on 2024-11-15 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0022_cardpost_is_finalized'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='frame_completed',
        ),
    ]
