# Generated by Django 5.1.2 on 2024-10-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_title', models.CharField(max_length=100)),
                ('add_image', models.ImageField(upload_to='advertisements/')),
                ('add_link', models.URLField()),
            ],
        ),
    ]
