# Generated by Django 5.1.2 on 2024-10-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('earthApp', '0002_advertisement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='add_image',
            new_name='ad_image',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='add_link',
            new_name='ad_link',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='add_title',
            new_name='ad_title',
        ),
    ]
