# Generated by Django 5.1.2 on 2024-10-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earthApp', '0003_rename_add_image_advertisement_ad_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('sticker', '스티커'), ('theme', '테마'), ('frame', '프레임')], max_length=10),
        ),
    ]
